### ISSUE TITLE
php command not found

### ISSUE THREAD

**Issue by thomaslc66** [rcdailey/nextcloud-cronjob#19]
Hello,

I've downloaded and installed your docker app from the app in Unraid and I think it's cool, so thank you for that.

I was just wondering if you know why I'm having a `php: command not found` in the console logs and also when I try to run php in the cli?

![image](https://user-images.githubusercontent.com/9827392/221890898-98edd782-9c96-4152-9424-f3b7f2acb055.png)

Thank you for your input.

**Comment by rcdailey** [comment]
~~Because `php` is not installed in the docker image by default. You should do an `apk add` for the php package as part of your cron script.~~

Ignore the above response... I misunderstood your question.

**Comment by thomaslc66** [comment]
Is there some kind of example in the readme ?

**Comment by rcdailey** [comment]
My last response was wrong, I misunderstood your question. My apologies.

I'm honestly not sure what your issue is. Clearly the php command is not available in your nextcloud container for some reason. I'm not sure. Can you try running the command manually in your nextcloud container? Do a `docker exec` to run the `php -f /var/www/html/cron.php` command and see what happens.

I can say for sure this is an issue with your setup and not with nextcloud-cronjob. Works fine for me and I didn't have to do anything special IIRC.

**Comment by thomaslc66** [comment]
Seems like it, 

First of all I'm a bit confused on where the script is actually stored and where it is run from. Last I think it's probably because I have php8 install as a command but I've not linked it to php command.

So if I understand it correctly the php -f /var/www/html/cron.php will be triggered from the nextcloud-cronjob but inside my nextcloud instance?

So then if I use php8 on my nextcloud instance and if my path is /config/www/nextcloud/cron.php I should edit the run-cron-php.sh script ? 
Maybe I can use this in the unraid ?
![image](https://user-images.githubusercontent.com/9827392/221896286-0678c2b2-2076-45a5-b255-733a53821d28.png)
