### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by jelle619** [rcdailey/nextcloud-cronjob#5]
At the moment, it seems like the ARM architecture is not supported by the image currently on Docker Hub. It would be great if support could be added, for I would like to use it on my Raspberry Pi.

**Comment by rcdailey** [comment]
This is a very reasonable ask. I'll look into setting up a build pipeline for it.

**Comment by rcdailey** [comment]
Looks like Docker Hub does not support multi-architecture builds yet. This issue seems to track it:
https://github.com/docker/roadmap/issues/109

Looks like demand for this is going up with Apple announcing new macs will be loaded with ARM processors. I'd keep an eye on this. Everything I'm seeing that is a workaround involves a lot of work.

**Comment by jelle619** [comment]
Thanks for looking into it.

**Comment by rcdailey** [comment]
@jelle619 Could you please test the newly added ARM 64-bit support and let me know if it is working? I unfortunately do not have an ARM device to test on!

**Comment by jelle619** [comment]
On it. I'll let you know soon. Thanks for the effort! @rcdailey

**Comment by jelle619** [comment]
It appears to be working. Thanks!
