### ISSUE TITLE
Azure webapp for containers

### ISSUE THREAD

**Issue by nickelnext** [rcdailey/nextcloud-cronjob#7]
Here my Yaml

_version: '3.8' 
services:
  db:
    image: mysql:5.7.31
    command: mysqld --sql-mode=NO_AUTO_VALUE_ON_ZERO
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=xxxxxxx
      - MYSQL_USER=xxxxxxxxx
    volumes:
       - ${WEBAPP_STORAGE_HOME}/mysql:/var/lib/mysql
    restart: always
  app:
    image: nextcloud:18.0.9
    ports: 
      - 80:80
    environment:
      - MYSQL_DATABASE=xxxxxxxx
      - MYSQL_USER=xxxxxxx
      - MYSQL_PASSWORD=xxxxxx
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=mydomain.net
      - NEXTCLOUD_DATA_DIR=/var/www/html/data/NextCloudData
    restart: always
    volumes:
      - CloudData:/var/www/html/data/NextCloudData
      - ${WEBAPP_STORAGE_HOME}/nextcloud/config:/var/www/html/config
      - ${WEBAPP_STORAGE_HOME}/nextcloud/apps:/var/www/html/custom_apps
  cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_EXEC_SHELL_ARGS=-xc
      - NEXTCLOUD_CONTAINER_NAME=app
      - NEXTCLOUD_EXEC_SHELL=sh_

I get 

`Container logs from xxxxxx_cron_0_3e7a4656 = 2020-10-07T20:19:27.777456415Z Container Name: app
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERROR: Unable to find the Nextcloud container
Container Name: app`

**Comment by rcdailey** [comment]
I'm pretty sure this container isn't going to work in a cloud environment. Basically, it needs direct access to the unix socket for docker. If you're running this service on a node that does not also contain the Docker Daemon, and furthermore the Nextcloud service itself, it will not work. I'm not sure if this fits your situation, but I wanted to mention it since your issue title hints at it.

The error we see here indicates to me that you do not have a docker daemon running on that node, or you do not have access to it for some reason. You have mapped it to a volume which is correct.

**Comment by nickelnext** [comment]
Hi thanks for your prompt response.

So do you have a solution for me? Or a suggestion on how to run the cron.php? Cause i can't find a solution rn :(

**Comment by rcdailey** [comment]
Find the path that your docker daemon Unix socket is located. Use that
path. This is an issue outside the scope of this project.
